language: julia
notifications:
  email: false
matrix:
  include:
    - os: linux
      julia: 0.5
      env: TESTCMD="xvfb-run julia"
    # - os: linux
    #   julia: nightly
    #   env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.5
      env: TESTCMD="julia"
    # - os: osx
    #   julia: nightly
    #   env: TESTCMD="julia"
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("Blink"); import Blink; Pkg.test("Blink"; coverage=true)'
